name = "adamodbus_tls"
description = "TLS transport for AdaModbus (Modbus/TCP Security)"
version = "1.0.0"
licenses = "MIT"
authors = ["Florian Fischer <florian.j.a.fischer@icloud.com>"]
maintainers = ["Florian Fischer <florian.j.a.fischer@icloud.com>"]
maintainers-logins = ["flottflo"]

tags = ["modbus", "tls", "ssl", "security", "tcp"]

project-files = ["adamodbus_tls.gpr"]

[gpr-externals]
ADAMODBUS_BUILD_MODE = ["debug", "release"]

[gpr-set-externals]
SOCKET = "openssl"

[[depends-on]]
adamodbus = "^1.0.0"

[[depends-on]]
aws = "^25.2.0"
