name = "adamodbus"
description = "SPARK-verified Ada 2022 Modbus library for embedded systems"
version = "1.0.0"
licenses = "MIT"
authors = ["Florian Fischer <florian.j.a.fischer@icloud.com>"]
maintainers = ["Florian Fischer <florian.j.a.fischer@icloud.com>"]
maintainers-logins = ["flottflo"]

tags = ["modbus", "embedded", "protocol", "serial", "tcp", "spark", "industrial"]

# For TLS support, use the separate adamodbus_tls crate

[gpr-externals]
ADAMODBUS_BUILD_MODE = ["debug", "release"]

[gpr-set-externals]
ADAMODBUS_BUILD_MODE = "debug"

[[depends-on]]
gnat = ">=12"

[[depends-on]]
aunit = "^26.0.0"
